import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#0d0d0d',
  '--slot4-page-text': '#fafafa',
  '--slot4-panel-bg': '#171717',
  '--slot4-surface-bg': '#fafafa',
  '--slot4-muted-text': '#fafafabf',
  '--slot4-soft-muted-text': '#fafafa80',
  '--slot4-accent': '#cc1c4b',
  '--slot4-accent-fill': '#cc1c4b',
  '--slot4-accent-soft': '#c6a6ff',
  '--slot4-on-accent': '#fafafa',
  '--slot4-dark-bg': '#0d0d0d',
  '--slot4-dark-text': '#fafafa',
  '--slot4-media-bg': '#232323',
  '--slot4-cream': '#fafafa',
  '--slot4-warm': '#f2f0ed',
  '--slot4-lavender': '#c6a6ff',
  '--slot4-gray': '#0d0d0d08',
  '--slot4-blue': '#364dcc',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#0d0d0d',
  '--editable-page-text': '#fafafa',
  '--editable-container': '1320px',
  '--editable-border': '#fafafa26',
  '--editable-border-dark': '#0d0d0d1a',
  '--editable-nav-bg': '#0d0d0d',
  '--editable-nav-text': '#fafafa',
  '--editable-nav-active': '#cc1c4b',
  '--editable-nav-active-text': '#fafafa',
  '--editable-cta-bg': '#cc1c4b',
  '--editable-cta-text': '#fafafa',
  '--editable-search-bg': '#fafafa',
  '--editable-footer-bg': '#0d0d0d',
  '--editable-footer-text': '#fafafa',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[#0d0d0d]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  lightBorder: 'border-[var(--editable-border-dark)]',
  darkBorder: 'border-white/15',
  overlay: 'bg-[linear-gradient(180deg,rgba(13,13,13,0.02),rgba(13,13,13,0.78))]',
} as const

export const editableDesignContract = {
  shell: {
    page: 'min-h-screen bg-[var(--slot4-page-bg)] text-[var(--slot4-page-text)]',
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-5 sm:px-6 lg:px-8',
    sectionY: 'py-20 sm:py-24 lg:py-32',
    sectionYSmall: 'py-12 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-5 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-0 lg:grid-cols-[0.95fr_1.05fr] lg:items-stretch',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[240px] shrink-0 snap-start sm:w-[300px]',
  },
  type: {
    eyebrow: 'text-xs font-medium uppercase tracking-[0.22em]',
    heroTitle: 'editable-display text-[3.25rem] font-normal leading-[1.15] tracking-[-0.04em] sm:text-[4.75rem] lg:text-[5.75rem]',
    sectionTitle: 'editable-display text-[2.6rem] font-normal leading-[1.15] tracking-[-0.04em] sm:text-[3.6rem] lg:text-[4.5rem]',
    h3: 'editable-display text-3xl font-normal leading-[1.15] tracking-[-0.04em]',
    body: 'text-base leading-[1.24] sm:text-lg',
    emphasis: 'editable-display font-normal leading-[1.15] tracking-[-0.04em]',
  },
  surface: {
    card: 'rounded-[1.5rem] border border-[var(--editable-border-dark)] bg-[var(--slot4-surface-bg)] text-[#0d0d0d]',
    soft: 'rounded-[1.5rem] border border-[var(--editable-border-dark)] bg-[#0d0d0d08] text-[#0d0d0d]',
    dark: 'rounded-[1.5rem] border border-white/15 bg-[var(--slot4-dark-bg)] text-[var(--slot4-dark-text)]',
  },
  button: {
    primary: 'inline-flex items-center justify-center gap-3 rounded-full bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-medium uppercase tracking-[0.12em] text-[var(--slot4-on-accent)] transition duration-500 hover:bg-[#fafafa] hover:text-[#0d0d0d]',
    secondary: 'inline-flex items-center justify-center gap-3 rounded-full border border-current/20 px-6 py-3 text-sm font-medium uppercase tracking-[0.12em] transition duration-500 hover:bg-current hover:text-[var(--slot4-page-bg)]',
    accent: 'inline-flex items-center justify-center gap-3 rounded-full bg-[var(--slot4-accent-soft)] px-6 py-3 text-sm font-medium uppercase tracking-[0.12em] text-[#0d0d0d] transition duration-500 hover:bg-[var(--slot4-blue)] hover:text-white',
    ghost: 'inline-flex items-center justify-center gap-2 rounded-full px-4 py-2 text-sm font-medium uppercase tracking-[0.12em] transition duration-500 hover:bg-current/10',
  },
  badge: {
    pill: 'rounded-full border border-current/15 px-3 py-1 text-xs font-medium uppercase tracking-[0.16em]',
    accentPill: 'rounded-full bg-[var(--slot4-accent-soft)] px-3 py-1 text-xs font-medium uppercase tracking-[0.16em] text-[#0d0d0d]',
  },
  media: {
    frame: 'relative overflow-hidden rounded-[1.5rem] bg-[var(--slot4-media-bg)]',
    frameFull: 'relative overflow-hidden rounded-[2rem] bg-[var(--slot4-media-bg)]',
    ratio: 'aspect-[4/3]',
  },
  motion: {
    lift: 'transition duration-500 hover:-translate-y-1 hover:shadow-[0_18px_60px_rgba(13,13,13,0.18)]',
    fade: 'transition duration-500 hover:opacity-75',
    zoom: 'transition duration-700 group-hover:scale-[1.045]',
  },
} as const

export const aiLayoutRules = [
  'Reference tokens live in /tmp/reference-tokens.md and map into CSS variables before JSX.',
  'Keep post fetching and route helpers unchanged; redesign only editable presentation.',
  'Use Tilt Warp display type, Host Grotesk body type, pill buttons, hard black/off-white bands, and red/blue/lavender accents.',
  'Navigation stays static-page only; task archives appear in footer discovery surfaces.',
  'Listing display label is Places and guide display label is Guides.',
] as const
